name = "outerfaith/format_number"
version = "0.1.0"
description = "Number formatting for Roblox"
authors = ["Outerfaith", "Blockzez"]
repository = "https://github.com/outerfaith/format-number"
license = "BSD 2-Clause"

includes = [
  "pesde.toml",
  "LICENSE.md",
  "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.3.0", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
